# Generated by Django 3.2.13 on 2022-11-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('release_date', models.DateField()),
                ('popularity', models.FloatField()),
                ('adult', models.BooleanField()),
                ('vote_count', models.IntegerField()),
                ('vote_average', models.FloatField()),
                ('backdrop_path', models.CharField(max_length=200)),
                ('poster_path', models.CharField(max_length=200)),
                ('original_language', models.CharField(max_length=100)),
                ('original_title', models.CharField(max_length=100)),
                ('netflix', models.BooleanField()),
                ('watcha', models.BooleanField()),
                ('wavve', models.BooleanField()),
                ('disney', models.BooleanField()),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.Genre')),
            ],
        ),
    ]
