# Generated by Django 3.2.13 on 2022-11-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ott',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='disney',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='netflix',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='watcha',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='wavve',
        ),
        migrations.AddField(
            model_name='movie',
            name='otts',
            field=models.ManyToManyField(related_name='movies', to='movies.Ott'),
        ),
    ]
