# Generated by Django 3.2.13 on 2022-11-18 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20221118_0924'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='using_otts',
            field=models.ManyToManyField(related_name='using_users', to='movies.Ott'),
        ),
    ]
